services:
  backend:
    build:
      context: ./event-planner-backend
    container_name: event-planner-api
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=event_planner_DB
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./event-planner-frontend
    container_name: event-planner-ui
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    container_name: event-planner-db
    environment:
      - MYSQL_DATABASE=event_planner_DB
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
